[package]
name = "auth-oauth"
description = "OAuth authentication provider for Auth."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
