[package]
name = "auth-credentials"
description = "Credentials authentication provider for Auth."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
