[package]
name = "shield-oauth"
description = "OAuth provider for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oauth2 = "4.4.2"
