[package]
name = "shield-seaorm"
description = "SeaORM storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true

[features]
default = []
entity = []
