[package]
name = "shield-leptos"
description = "Leptos integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos_actix = { workspace = true, optional = true }
leptos_axum = { workspace = true, optional = true }
shield = { path = "../../core/shield" }
shield-axum = { path = "../shield-axum", optional = true }

[features]
default = []
actix = ["dep:leptos_actix"]
axum = ["dep:leptos_axum", "dep:shield-axum"]
