[package]
name = "shield-oidc"
description = "OpenID Connect provider for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
openidconnect = "3.5.0"
