[book]
authors = ["Daniëlle Huisman"]
language = "en"
multilingual = false
src = "src"
title = "Auth"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css", "theme/theme.css"]
additional-js = ["theme/tabs.js"]
edit-url-template = "https://github.com/RustForWeb/auth/edit/main/book/{path}"
git-repository-url = "https://github.com/RustForWeb/auth"

[rust]
edition = "2021"
